In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

In [2]:
user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'
headers = {'User-Agent': user_agent}

director_url = 'https://www.bfi.org.uk/sight-and-sound/directors-100-greatest-films-all-time'
critics_url = 'https://www.bfi.org.uk/sight-and-sound/greatest-films-all-time'

# pattern to identify year and place
pattern = re.compile(r'(\d{4})\s(.*)')

In [3]:
'''
d_content = requests.get(director_url, headers=headers).content
c_content = requests.get(critics_url, headers=headers).content
'''

'\nd_content = requests.get(director_url, headers=headers).content\nc_content = requests.get(critics_url, headers=headers).content\n'

In [4]:
'''
with open('directors.html', 'wb') as f:
    f.write(d_content)
with open('critics.html', 'wb') as f:
    f.write(c_content)
'''

"\nwith open('directors.html', 'wb') as f:\n    f.write(d_content)\nwith open('critics.html', 'wb') as f:\n    f.write(c_content)\n"

In [5]:
d_content = open('directors.html', 'rb').read()
c_content = open('critics.html', 'rb').read()

d_list = BeautifulSoup(d_content, 'html.parser').find_all('article')
c_list = BeautifulSoup(c_content, 'html.parser').find_all('article')

In [6]:
rank_arr = []
name_arr = []
description_arr = []
time_arr = []
place_arr = []
director_arr = []

for film in d_list:
    name = film.find('h1').text
    info_list = film.find_all('p')
    rank = info_list[0].text[1:] if info_list[0].text[0] == '=' else info_list[0].text
    description = info_list[1].text
    time_and_place = info_list[2].text
    m = re.match(pattern, time_and_place)
    time = m.group(1)
    place = m.group(2)
    # remove 'directed by'
    director = info_list[3].text[12:]
    
    print(name)
    rank_arr.append(int(rank))
    name_arr.append(name)
    description_arr.append(description)
    time_arr.append(int(time))
    place_arr.append(place)
    director_arr.append(director)

d_pd = pd.DataFrame({'rank': rank_arr,
                     'name': name_arr, 
                     'description': description_arr, 
                     'time': time_arr, 
                     'place': place_arr, 
                     'director': director_arr})

Throne of Blood
Yi Yi
Pickpocket
Battleship Potemkin
Wanda
TA'AME-GILAS...
Parasite
Hidden
The Conformist
The Colour of Pomegranates
Moonlight
Eternal Sunshine of the Spotless Mind
The Ascent
The Red Shoes
Wild Strawberries
Shoah
The Spirit of the Beehive
Blue Velvet
News from Home
Modern Times
Sans Soleil
A Brighter Summer Day
Touki Bouki
The Searchers
Where is the Friend's House?
 Kes
A Separation
Salò, or the 120 Days of Sodom
The Conversation
L'Argent
Ikiru
The Seventh Seal
Chinatown
Jaws
Some Like It Hot
Lawrence of Arabia
 Blade Runner
Tropical Malady
Sátántangó
La ciénaga
Sunset Blvd.
Meshes of the Afternoon
Late Spring
Eraserhead
Fanny and Alexander
Cléo from 5 to 7
Viridiana
Fear Eats the Soul
The Piano
La notte
Singin' in the Rain
La Maman et la Putain
Don't Look Now
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb
Psycho
L'Atalante
City Lights
Once upon a Time in the West
Le Mépris
Come and See
Vagabond
A Man Escaped
The Night of the Hunter
Playtime
L'avventura
La Règle du jeu
La strada
Au hasard Balthazar
La dolce vita
La Jetée
The 400 Blows
Sunrise: A Song of Two Humans
Man with a Movie Camera
The Passion of Joan of Arc
Ordet
Do the Right Thing
GoodFellas
The Godfather Part II
Andrei Rublev
Raging Bull
Pather Panchali
Mulholland Dr.
The Battle of Algiers
Bicycle Thieves
Rashomon
A Woman under the Influence
Apocalypse Now
Stalker
À bout de souffle
Seven Samurai
Beau travail
Barry Lyndon
Taxi Driver
Close-up
In the Mood for Love
Persona
Mirror
8½
Vertigo
Jeanne Dielman  23, quai du Commerce, 1080 Bruxelles
Tokyo Story
The Godfather
Citizen Kane
2001: A Space Odyssey

In [7]:
rank_arr = []
name_arr = []
description_arr = []
time_arr = []
place_arr = []
director_arr = []

for film in c_list:
    name = film.find('h1').text
    info_list = film.find_all('p')
    rank = info_list[0].text[1:] if info_list[0].text[0] == '=' else info_list[0].text
    description = info_list[1].text
    time_and_place = info_list[2].text
    m = re.match(pattern, time_and_place)
    time = m.group(1)
    place = m.group(2)
    # remove 'directed by'
    director = info_list[3].text[12:]
    
    rank_arr.append(int(rank))
    name_arr.append(name)
    description_arr.append(description)
    time_arr.append(int(time))
    place_arr.append(place)
    director_arr.append(director)

c_pd = pd.DataFrame({'rank': rank_arr,
                     'name': name_arr, 
                     'description': description_arr, 
                     'time': time_arr, 
                     'place': place_arr, 
                     'director': director_arr})

In [8]:
c_pd.sort_values(by='rank', ascending=True, inplace=True)
c_pd.head().style.hide_index()

C:\Users\gargu\AppData\Local\Temp\ipykernel_25736\561892499.py:2: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  c_pd.head().style.hide_index()

In [9]:
d_pd.sort_values(by='rank', ascending=True, inplace=True)
d_pd.head().style.hide_index()

C:\Users\gargu\AppData\Local\Temp\ipykernel_25736\3742028762.py:2: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  d_pd.head().style.hide_index()

In [12]:
merged = c_pd.copy(deep=True)
merged = pd.concat([d_pd, merged]).drop_duplicates(subset=['name'], keep='first')
merged

,rank,name,description,time,place,director
103,1,2001: A Space Odyssey,Stanley Kubrick’s grand vision of mankind’s jo...,1968,"USA, United Kingdom",Stanley Kubrick
102,2,Citizen Kane,Famously sitting at the top of the Sight and S...,1941,USA,Orson Welles
101,3,The Godfather,The first of Francis Ford Coppola’s epic trilo...,1972,USA,Francis Ford Coppola
100,4,Tokyo Story,Told in Yasujirō Ozu’s simple and elegant styl...,1953,Japan,Yasujirō Ozu
99,4,"Jeanne Dielman 23, quai du Commerce, 1080 Bru...",A magnificent epic of experimental cinema offe...,1975,"Belgium, France",Chantal Akerman
...,...,...,...,...,...,...
7,90,The Leopard,Luchino Visconti’s sumptuous epic portrays the...,1963,"Italy, France",Luchino Visconti
6,90,Madame de...,Max Ophuls’ woozy whirligig tracks a pair of u...,1953,"France, Italy",Max Ophuls
2,95,Black Girl,Ousmane Sembène lifts the mask on France’s rac...,1965,"Senegal, France",Ousmane Sembène
1,95,The General,Buster Keaton’s most lavish production and his...,1926,USA,"Buster Keaton, Clyde Bruckman"
0,95,Get Out,"A poster film for Black Lives Matter, Jordan P...",2017,"USA, Japan",Jordan Peele

In [20]:
place_dict = {}

for place in merged['place']:
    places = place.split(', ')
    for p in places:
        if p in place_dict:
            place_dict[p] += 1
        else:
            place_dict[p] = 1

print({k: v for k, v in sorted(place_dict.items(), key=lambda item: item[1], reverse=True)})

{'USA': 46, 'France': 42, 'Italy': 19, 'Japan': 13, 'United Kingdom': 11, 'USSR': 8, 'Sweden': 5, 'Germany': 5, 'Switzerland': 5, 'Iran': 4, 'Hong Kong': 3, 'Federal Republic of Germany': 3, 'Spain': 3, 'Belgium': 2, 'Taiwan': 2, 'Senegal': 2, 'Algeria': 1, 'India': 1, 'Denmark': 1, 'Australia': 1, 'Mexico': 1, 'Thailand': 1, 'Argentina': 1, 'Brazil': 1, 'Hungary': 1, 'Austria': 1, 'Republic of Korea': 1, 'Czechoslovakia': 1}

In [28]:
director_dict = {}

for director in merged['director']:
    directors = director.split(', ')
    for d in directors:
        if d in director_dict:
            director_dict[d] += 1
        else:
            director_dict[d] = 1

print({k: v for k, v in sorted(director_dict.items(), key=lambda item: item[1], reverse=True)})

{'Stanley Kubrick': 4, 'Francis Ford Coppola': 4, 'Alfred Hitchcock': 4, 'Ingmar Bergman': 4, 'Jean-Luc Godard': 4, 'Akira Kurosawa': 4, 'Robert Bresson': 4, 'Federico Fellini': 3, 'Andrei Tarkovsky': 3, 'Abbas Kiarostami': 3, 'Martin Scorsese': 3, 'David Lynch': 3, 'Agnès Varda': 3, 'Billy Wilder': 3, 'Yasujirō Ozu': 2, 'Chantal Akerman': 2, 'Wong Kar Wai': 2, 'Carl Th. Dreyer': 2, 'Chris Marker': 2, 'Michelangelo Antonioni': 2, 'Charles Chaplin': 2, 'Michael Powell': 2, 'Emeric Pressburger': 2, 'Edward Yang': 2, 'Fritz Lang': 2, 'Buster Keaton': 2, 'Hayao Miyazaki': 2, 'Kenji Mizoguchi': 2, 'Orson Welles': 1, 'Claire Denis': 1, 'John Cassavetes': 1, 'Vittorio De Sica': 1, 'Gillo Pontecorvo': 1, 'Satyajit Ray': 1, 'Spike Lee': 1, 'Dziga Vertov': 1, 'F.W. Murnau': 1, 'François Truffaut': 1, 'Jean Renoir': 1, 'Charles Laughton': 1, 'Elem Klimov': 1, 'Jacques Tati': 1, 'Nicolas Roeg': 1, 'Sergio Leone': 1, 'Jean Vigo': 1, 'Jean Eustache': 1, 'Jane Campion': 1, 'Rainer Werner Fassbinder': 1, 'Luis Buñuel': 1, 'Gene Kelly': 1, 'Stanley Donen': 1, 'Steven Spielberg': 1, 'David Lean': 1, 'Apichatpong Weerasethakul': 1, 'Ridley Scott': 1, 'Lucrecia Martel': 1, 'Maya Deren': 1, 'Alexander Hackenschmied': 1, 'Béla Tarr': 1, 'Larissa Shepitko': 1, 'Claude Lanzmann': 1, 'Víctor Erice': 1, 'John Ford': 1, 'Ken Loach': 1, 'Asghar Farhadi': 1, 'Pier Paolo Pasolini': 1, 'Roman Polanski': 1, 'Djibril Diop Mambéty': 1, 'Sergei M. Eisenstein': 1, 'Barbara Loden': 1, 'Barry Jenkins': 1, 'Michael Haneke': 1, 'Bernardo Bertolucci': 1, 'Sergei Paradjanov': 1, 'Michel Gondry': 1, 'Bong Joon-ho': 1, 'Věra Chytilová': 1, 'Céline Sciamma': 1, 'Charles Burnett': 1, 'Julie Dash': 1, 'Michael Curtiz': 1, 'Carol Reed': 1, 'Roberto Rossellini': 1, 'Douglas Sirk': 1, 'Jacques Rivette': 1, 'Luchino Visconti': 1, 'Max Ophuls': 1, 'Ousmane Sembène': 1, 'Clyde Bruckman': 1, 'Jordan Peele': 1}

In [31]:
year_dict = {}

for year in merged['time']:
    if year in year_dict:
        year_dict[year] += 1
    else:
        year_dict[year] = 1

print({k: v for k, v in sorted(year_dict.items(), key=lambda item: item[1], reverse=True)})

{1974: 6, 1975: 5, 1966: 5, 1960: 5, 1954: 5, 1959: 5, 1963: 4, 1976: 4, 1973: 4, 1968: 3, 1953: 3, 2001: 3, 1955: 3, 1927: 3, 1962: 3, 1985: 3, 1982: 3, 2004: 3, 1957: 3, 2000: 2, 1989: 2, 1979: 2, 1950: 2, 1948: 2, 1980: 2, 1956: 2, 1931: 2, 1961: 2, 1949: 2, 1994: 2, 1991: 2, 1970: 2, 2019: 2, 1988: 2, 1965: 2, 1941: 1, 1972: 1, 1958: 1, 1998: 1, 1990: 1, 1929: 1, 1939: 1, 1967: 1, 1934: 1, 1992: 1, 1951: 1, 1943: 1, 1986: 1, 1936: 1, 1987: 1, 1969: 1, 2011: 1, 1983: 1, 1952: 1, 1999: 1, 1925: 1, 1997: 1, 2016: 1, 1977: 1, 1924: 1, 1942: 1, 1946: 1, 1926: 1, 2017: 1}